name: aqueduct_upload
description: A upload controller for Aqueduct apps.
version: 2.0.0
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  conduit: ^2.0.0-b1
  translit: ^2.0.0
  
dev_dependencies:
  test: ^1.16.0
