name: aqueduct_upload
description: A upload controller for Aqueduct apps.
version: 0.1.0
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/
environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  aqueduct: ^3.0.0
  translit: ^1.3.0
  
dev_dependencies:
  test: ^1.6.0
